{% set name = "flask-flatpages" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2290214395a2ef43f9d844db07fc97f314baff807864e67f665ac5c4c938f392

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - flask >1.0
    - jinja2 >=2.10.2
    - markdown >=2.5
    - pyyaml >5.3.1
    - six

test:
  imports:
    - flask_flatpages
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SimonSapin/Flask-FlatPages
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Provides flat static pages to a Flask application
  dev_url: https://github.com/SimonSapin/Flask-FlatPages
  doc_url: https://flask-flatpages.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
