schema_version: 1

context:
  name: flask-flatpages
  version: "0.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 2290214395a2ef43f9d844db07fc97f314baff807864e67f665ac5c4c938f392

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - flask >1.0
    - jinja2 >=2.10.2
    - markdown >=2.5
    - pyyaml >5.3.1
    - six

tests:
  - python:
      imports:
        - flask_flatpages
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Provides flat static pages to a Flask application
  homepage: https://github.com/SimonSapin/Flask-FlatPages
  repository: https://github.com/SimonSapin/Flask-FlatPages
  documentation: https://flask-flatpages.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
