# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jff4aHRmHuAclotrnEvSE7ZhjjsDoBFD6YPws8cB+IvBC7/T1JApdlNrYE/NrMhSBvYDyvGos+4GNbr6jDBqQ5J6NsceGeAsndRMTOWSs/w5y4qKX+Tt/y4+hUOuKN5WJD+8Z3mtQFceq56cWSpSUDQ3lW5ooZqDDpNMq9uJtMh0hnpmWf9A8m11OZiwtlypJtBEVhaLAUXLf+E4Vm0ILkuHtBAEqgl+CV6zapcW2/4Cl27bHpmUdfM0FbW6UllPygRCDUwyS41rgKztMJQ5Qgj3gcQK80PBQLxvi8u6hWgNvUKvPje0MkTLCRlsXOajZSnkxGL55xRTn2148+IP09bXIsnqd0u4xvt58OzsnxEgV9nQFL5fGMTt6KcJn+nW/PgkTUB5baPWsccs/Cpt/cXo/hbKIneAaqVaLpkd0HVK0YIDpS2QKX4SiI7Nc9NmjSCuwN+Hh38wBp3eWw/cVHLMevTS+ArLNMcDf28AHAObEuRCd6YdEj9nUcCFMX2i/fCnJ/5xE4gfql6q/cD+GBzO/mwd1YZr8/Bd8OIVyXF0lF6qZSaGsWCQzUxqgZQrhaqaIGUDdH/P9uAJL1K1jRwIQSHIM7RUqxvg0zrYsG7fUKEvclTVxZh0Q/7Y6J0KSRoqrQP9WrfpA2mG2yeDOuIjYHfr75pMnTOKnWx3JCM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
