appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qngQGzM48j3Ai/d7Mz6Q1jpXgjKjYHWBFpahKSr1dYJgZmgHAGoOQ3ZTufC5YSMND8aMGbxVW7iw6OnG8THQUKkzDlq9GCjlc9zrCAhgGOCzkcUCSdX7hxvfUWsmcK+Grcy3wQ6PN1/ueGszU2yoyxQxq/9qv1KMdd9ebw07oZKDgBwHSFjy1tD+ex/SIna9Vl23YxcAVp7wiXpMdK8fau+MjeW3YO7nQBjHY8yzamOOYwuxiV2uxDRGUDNYioZ0uB2Dks5yD3WCT0o+G3ee+SK5lUO1iLLZxUYtgqukX/5xqVFjkXNjs4l2JwHjfNE9Y/zv26B3NvQf1Dfn1hTxTqJqD06pPDDmKfXG3IyCzA5XyIGsloo6iUwnBw0uWozqyC+QeFmrAyyCMBDSLPQBkeWEHaF1VRs2p9GB9h/UYDOq5wLpNpJF0U8/Gz86npWHTImv+UYNioYTZRDquH4dpoHP5XKhwIwrwFPHR3L289bVEQZ3qceNCHjiwyLOMuuKP8TUSO7lTLBByuvVW1QVJT51k4iiQv/AWmqKxm6EDDSQ0OizkwOmsrMp4yzjChpB+rMr3ELmCKTnM893W3j5kIBYXYjzHOWCWIOMjSQXXeqvb27EYFByC9A+KPnm7mmXPGwbLWAHl4V8ZTIHb5pFcm8SG2Nc93W7HxvlqfzblXc=}
