travis:
  secure:
    BINSTAR_TOKEN: jff4aHRmHuAclotrnEvSE7ZhjjsDoBFD6YPws8cB+IvBC7/T1JApdlNrYE/NrMhSBvYDyvGos+4GNbr6jDBqQ5J6NsceGeAsndRMTOWSs/w5y4qKX+Tt/y4+hUOuKN5WJD+8Z3mtQFceq56cWSpSUDQ3lW5ooZqDDpNMq9uJtMh0hnpmWf9A8m11OZiwtlypJtBEVhaLAUXLf+E4Vm0ILkuHtBAEqgl+CV6zapcW2/4Cl27bHpmUdfM0FbW6UllPygRCDUwyS41rgKztMJQ5Qgj3gcQK80PBQLxvi8u6hWgNvUKvPje0MkTLCRlsXOajZSnkxGL55xRTn2148+IP09bXIsnqd0u4xvt58OzsnxEgV9nQFL5fGMTt6KcJn+nW/PgkTUB5baPWsccs/Cpt/cXo/hbKIneAaqVaLpkd0HVK0YIDpS2QKX4SiI7Nc9NmjSCuwN+Hh38wBp3eWw/cVHLMevTS+ArLNMcDf28AHAObEuRCd6YdEj9nUcCFMX2i/fCnJ/5xE4gfql6q/cD+GBzO/mwd1YZr8/Bd8OIVyXF0lF6qZSaGsWCQzUxqgZQrhaqaIGUDdH/P9uAJL1K1jRwIQSHIM7RUqxvg0zrYsG7fUKEvclTVxZh0Q/7Y6J0KSRoqrQP9WrfpA2mG2yeDOuIjYHfr75pMnTOKnWx3JCM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
